HazeltineStorage/Models/CustomerType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HazeltineStorage.Models
{
    public class CustomerType
    {
        [Key]
        public byte Id { get; set; }

        [Display(Name = "Customer Type")]
        public string TypeDescription { get; set; }

        public IList<Customer> Customer { get; set; }
    }
}

HazeltineStorage/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HazeltineStorage.Models;

namespace HazeltineStorage.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public ActionResult Index()
        {
            var customers = db.Customers.Include(c => c.CustomerStatus).Include(c => c.CustomerType).Include(c => c.User);
            return View(customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Details/5
        public ActionResult DetailsReadOnly(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }



        // GET: Customers/Create
        public ActionResult Create()
        {
            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription");
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,CustomerTypeId,CustomerStatusId,FirstName,LastName,Address1,Address2,City,State,Zip,MainPhone,MobilePhone,TextNotification,EmailAddress,EmailNotification,EmailInvoice,CustomerBalance,CustomerNote")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription", customer.CustomerStatusId);
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription", customer.CustomerTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", customer.UserId);
            return View(customer);
        }

        //Brian added below code:

        // GET: Customers/Inquiry
        public ActionResult Inquire()
        {
            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription");
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Customers/NewInquiry
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inquire([Bind(Include = "Id,UserId,CustomerTypeId,CustomerStatusId,FirstName,LastName,Address1,Address2,City,State,Zip,MainPhone,MobilePhone,TextNotification,EmailAddress,EmailNotification,EmailInvoice,CustomerBalance,CustomerNote")] Customer customer)
        //public ActionResult Inquire([Bind(Include = "FirstName,LastName,MainPhone,MobilePhone,TextNotification,EmailAddress,EmailNotification,CustomerNote")] Customer customer)
        // I tried only listed items. It didn't work.
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");// redirect to thank you page.
            }

            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription", customer.CustomerStatusId);
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription", customer.CustomerTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", customer.UserId);
            return View(customer);
        }

        //Brian added above code.

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription", customer.CustomerStatusId);
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription", customer.CustomerTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", customer.UserId);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,CustomerTypeId,CustomerStatusId,FirstName,LastName,Address1,Address2,City,State,Zip,MainPhone,MobilePhone,TextNotification,EmailAddress,EmailNotification,EmailInvoice,CustomerBalance,CustomerNote")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription", customer.CustomerStatusId);
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription", customer.CustomerTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", customer.UserId);
            return View(customer);
        }

        //Brian code below:
        // GET: Customers/Manage/
        public ActionResult Manage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerStatusId = new SelectList(db.CustomerStatus, "Id", "StatusDescription", customer.CustomerStatusId);
            ViewBag.CustomerTypeId = new SelectList(db.CustomerTypes, "Id", "TypeDescription", customer.CustomerTypeId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", customer.UserId);
            return View(customer);
        }

        // POST: Customers/UpdateCustomerBalance/Id
        //Not sure why the following two lines need to be out in order for this method to work:
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult UpdateCustomerBalance([Bind(Include = "CustomerBalance")] int id)
        {
            Customer customer = db.Customers.Find(id);
            //The following two lines of code will fail if the customer has null of either invoices or payments.
            decimal? customerInvoicesTotal = db.Invoices.Where(i => i.CustomerId == customer.Id).Sum(i => i.TotalDue);
            decimal? customerPaymentsTotal = db.Payments.Where(p => p.CustomerId == customer.Id).Sum(p => p.AmountReceived);
            //example of similair code: viewModel.Contract.ContractTotal = db.StorageUnits.Where(su => su.ContractId == viewModel.Contract.Id).Sum(su => su.RentalRate);

            decimal? customerNetTotal = (customerInvoicesTotal - customerPaymentsTotal);

            customer.CustomerBalance = customerNetTotal;
            db.Entry(customer).State = EntityState.Modified;
            db.SaveChanges();

            //I am not sure why the following line works. "Manage" should accept an int not an object.
            return View("Manage", customer);
        }





        //Not used at the moment:
        //public ActionResult _SubmissionTab()
        //{
        //    return PartialView();
        //}

        //public ActionResult _SearchTab()
        //{
        //    return PartialView();
        //}



        //Brian code above.

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

HazeltineStorage/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HazeltineStorage.Models;

namespace HazeltineStorage.Controllers
{
    public class InvoicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Invoices
        public ActionResult Index()
        {
            var invoices = db.Invoices.Include(i => i.Customer);
            return View(invoices.ToList());
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoices/Details/5 Read Only
        public ActionResult DetailsReadOnly(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }


        // GET: Invoices/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "LastName");
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,InvoiceDate,ForMonthOf,IsPaid,TotalDue")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();

                //UpdateCustomerBalance helper method:
                UpdateCustomerBalance(invoice.CustomerId);

                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "LastName", invoice.CustomerId);
            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "LastName", invoice.CustomerId);
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerId,InvoiceDate,ForMonthOf,IsPaid,TotalDue")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();

                //UpdateCustomerBalance helper method:
                UpdateCustomerBalance(invoice.CustomerId);

                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "LastName", invoice.CustomerId);
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();

            //UpdateCustomerBalance helper method:
            UpdateCustomerBalance(invoice.CustomerId);

            return RedirectToAction("Index");
        }

        //POST: Invoices/UpdateCustomerCustomerBalance/Id helper method
        public void UpdateCustomerBalance([Bind(Include = "CustomerBalance")] int id)
        {
            Customer customer = db.Customers.Find(id);
            //The following two lines of code will fail if the customer has null of either invoices or payments.
            decimal? customerInvoicesTotal = db.Invoices.Where(i => i.CustomerId == customer.Id).Sum(i => i.TotalDue);
            decimal? customerPaymentsTotal = db.Payments.Where(p => p.CustomerId == customer.Id).Sum(p => p.AmountReceived);

            decimal? customerNetTotal = (customerInvoicesTotal - customerPaymentsTotal);

            customer.CustomerBalance = customerNetTotal;
            db.Entry(customer).State = EntityState.Modified;
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HazeltineStorage/Views/Customers/Inquire.cshtml
@model HazeltineStorage.Models.Customer

@{
    ViewBag.Title = "Inquire";
}

<h2>Inquire Here</h2>

@using (Html.BeginForm("Inquire", "Customers")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerTypeId, "CustomerTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerStatusId, "CustomerStatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerStatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerStatusId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.MainPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MainPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MainPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobilePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobilePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobilePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TextNotification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TextNotification)
                    @Html.ValidationMessageFor(model => model.TextNotification, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailNotification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailNotification)
                    @Html.ValidationMessageFor(model => model.EmailNotification, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.EmailInvoice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmailInvoice)
                    @Html.ValidationMessageFor(model => model.EmailInvoice, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerBalance, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerNote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerNote, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerNote, "", new { @class = "text-danger" })
            </div>
        </div>

        @*Hidden fields, this stopped error but it still doesn't save data.*@
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.CustomerTypeId)
        @Html.HiddenFor(model => model.CustomerStatusId)
        @Html.HiddenFor(model => model.Address1)
        @Html.HiddenFor(model => model.Address2)
        @Html.HiddenFor(model => model.City)
        @Html.HiddenFor(model => model.State)
        @Html.HiddenFor(model => model.Zip)
        @Html.HiddenFor(model => model.EmailInvoice)
        @Html.HiddenFor(model => model.CustomerBalance)


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Inquire" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HazeltineStorage/Views/Customers/Manage.cshtml
@model HazeltineStorage.Models.Customer

@{
    ViewBag.Title = "Manage Customer";
}

<h2>Manage</h2>

<div>
    <h4>Customer</h4>
    <hr />

    <div class="row">

        <div class="col-md-4">
            <dl class="dl-horizontal">

                <dt>
                    Full Name
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MainPhone)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.MainPhone)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MobilePhone)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.MobilePhone)
                </dd>
            </dl>
        </div>

        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CustomerType.TypeDescription)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CustomerType.TypeDescription)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CustomerStatus.StatusDescription)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CustomerStatus.StatusDescription)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CustomerBalance)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CustomerBalance)
                </dd>
            </dl>
        </div>

         <div class="col-md-4">
             @Html.ActionLink("Make A Payment", "ConfirmOnlinePayment", "Payments", new { id = Model.Id }, null)
             @*ActionLink(this HtmlHelper htmlHelper, string linkText, string actionName, string controllerName, object routeValues, object htmlAttributes);*@
             <p><a href="~/Paypal/Index" class="btn btn-primary btn-lg">Make A Payment</a></p>
             @Html.ActionLink("Update Customer Balance", "UpdateCustomerBalance", "Customers", new { id = Model.Id }, null)
         </div>

    </div>
</div>





        <!-- Tab Buttons -->
        <ul id="tabstrip" class="nav nav-tabs" role="tablist">
            <li class="active"><a href="#_CustomerInfoTab" role="tab" data-toggle="tab">Customer Info</a></li>

            <li><a href="#_ContractInfoTab" role="tab" data-toggle="tab">Contracts</a></li>

            <li><a href="#_InvoiceInfoTab" role="tab" data-toggle="tab">Invoices</a></li>

            <li><a href="#_PaymentInfoTab" role="tab" data-toggle="tab">Payments</a></li>

            <li><a href="#_ActivityInfoTab" role="tab" data-toggle="tab">Activity and Messages</a></li>
        </ul>

        <!-- Tab Content Containers -->
        <div class="tab-content">
            <div class="tab-pane fade in active" id="_CustomerInfoTab">@Html.Partial("_CustomerInfoTab")</div>

            <div class="tab-pane fade" id="_ContractInfoTab">@Html.Partial("_ContractInfoTab")</div>

            <div class="tab-pane fade" id="_InvoiceInfoTab">@Html.Partial("_InvoiceInfoTab")</div>

            <div class="tab-pane fade" id="_PaymentInfoTab">@Html.Partial("_PaymentInfoTab")</div>

            <div class="tab-pane fade" id="_ActivityInfoTab">@Html.Partial("_ActivityInfoTab")</div>
        </div>





        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

HazeltineStorage/Views/Customers/_InvoiceInfoTab.cshtml
@*@model IEnumerable<HazeltineStorage.Models.Invoice>*@
@model HazeltineStorage.Models.Customer

<p>
    @Html.ActionLink("Create New", "Create", "Invoices")
</p>

<p>
    Invoices for: 
    @Html.DisplayFor(model => model.FirstName)
    @Html.DisplayFor(model => model.LastName)
</p>

<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.Customer.UserId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Invoices.First().InvoiceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Invoices.First().ForMonthOf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Invoices.First().IsPaid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Invoices.First().TotalDue)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Invoices) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Customer.UserId)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.InvoiceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ForMonthOf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPaid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalDue)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "Invoices", new { id=item.Id }, null) |
            @Html.ActionLink("Details", "Details", "Invoices", new { id=item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", "Invoices", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>