HazeltineStorage/Controllers/HazeltineCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HazeltineStorage.Controllers
{
    public class HazeltineCustomerController : Controller
    {

        // GET: HazeltineCustomer
        public ActionResult Index()
        {
            return View();
        }

        // GET: HazeltineCustomer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HazeltineCustomer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HazeltineCustomer/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HazeltineCustomer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HazeltineCustomer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HazeltineCustomer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HazeltineCustomer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HazeltineStorage/Views/HazeltineCustomer/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>My Account at Hazeltine Storage</h2>

<br />
<hr />
<br />

<div class="row">

    <div class="col-md-3">

        <p><a href="~/Customers/DetailsReadOnly/8" class="btn btn-primary btn-lg">My Account Info</a></p>
        @*@Html.ActionLink("Details", "Details", "HazeltineCustomer", new { id = 2 })*@

    </div>
    <div class="col-md-3">

        <p><a href="~/Contracts/DetailsReadOnly/2" class="btn btn-primary btn-lg">My Contracts</a></p>

    </div>
    <div class="col-md-3">

        <p><a href="~/Invoices/DetailsReadOnly/1" class="btn btn-primary btn-lg">My Invoices</a></p>

    </div>
    <div class="col-md-3">

        <p><a href="~/Payments/DetailsReadOnly/1" class="btn btn-primary btn-lg">My Payments</a></p>

    </div>
</div>